"use client";
import {useState,useMemo,useEffect} from 'react';
import {GitCompare,FileText,Download,Images,X,ChevronRight,Check,RefreshCw} from 'lucide-react';
import {LOCATIONS,CLASSES,BANDS,BAND_LABELS,natural,condition,substrate,decision,band,pct,fmt,select,stats,summarize,galleryGroups,csv,DEFAULT_FILTERS} from './researchModel.mjs';
const POSITION_COLORS={1:'#6b5aca',4:'#238a9a',5:'#c58c3e',9:'#768598'};
const titleOf=(mode)=>mode==='reports'?'보고서 출력':'조건·위치 비교';
const delta=v=>v==null?'—':`${v>0?'+':''}${fmt(v)} pp`;
function Stack({s}){return <div className="rs-stack">{[['residue','#c15b64'],['non','#398e83'],['ambiguous','#d6a64e']].map(([k,c])=><i key={k} style={{background:c,width:`${s.n?100*s[k]/s.n:0}%`}}/>)}</div>}
function Legend(){return <div className="rs-legend"><span><i style={{background:'#c15b64'}}/>Residue</span><span><i style={{background:'#398e83'}}/>Non-residue</span><span><i style={{background:'#d6a64e'}}/>Ambiguous</span></div>}
function PillSet({values,value,set,labeler=x=>x}){const active=value===null?values:value;return <div className="rs-chips">{values.map(v=><button type="button" key={v} aria-pressed={active.includes(v)} className={active.includes(v)?'selected':''} onClick={()=>set(active.includes(v)?active.filter(x=>x!==v):[...active,v])}>{active.includes(v)&&<Check size={11}/>} {labeler(v)}</button>)}</div>}
function Metric({title,value,note}){return <div><small>{title}</small><b>{value}</b><span>{note}</span></div>}
function RateBar({label,value,upper,color='#526bb5',note,onClick}){return <button className="rs-rate-row" disabled={!onClick} onClick={onClick}><span>{label}</span><div className="rs-rate-track">{upper!=null&&<i className="rs-upper" style={{width:`${upper}%`,background:color}}/>}{value!=null&&<i style={{width:`${value}%`,background:color}}/>}</div><strong>{pct(value)}<small>{note}</small></strong></button>}
export default function ResearchTools({mode,points,filters,setFilters,classify,autoClass,scoreFn,renderEvidence,api,go,projectList=[],analysisActive}){
 const data=useMemo(()=>points.map(p=>({...p,_final:classify(p),_auto:autoClass(p),_score:typeof p.evaluation_score==='number'?p.evaluation_score:scoreFn(p),_human:CLASSES.includes(p.human_result)})),[points,classify,autoClass,scoreFn]);
 const [tab,setTab]=useState('conditions'),[axis,setAxis]=useState('all'),[fixed,setFixed]=useState(''),[baseline,setBaseline]=useState(''),[detail,setDetail]=useState(null),[detailPage,setDetailPage]=useState(0),[evidence,setEvidence]=useState(null),[previewGroup,setPreviewGroup]=useState(0);
 const [kind,setKind]=useState('points'),[includeVerification,setIncludeVerification]=useState(false),[perPage,setPerPage]=useState(12),[groupScores,setGroupScores]=useState(true),[groupConditions,setGroupConditions]=useState(true),[job,setJob]=useState(null),[error,setError]=useState(''),[submitting,setSubmitting]=useState(false);
 const patch=x=>setFilters({...filters,...x});
 const f=useMemo(()=>({...filters,...((mode!=='reports'||kind==='summary')?{results:null,score_bands:null}:{}),conditions:axis==='all'?filters.conditions:[...new Set(data.filter(p=>String(axis==='time'?p.power:p.time)===fixed).map(condition))].filter(k=>filters.conditions===null||filters.conditions.includes(k))}),[filters,mode,kind,axis,fixed,data]);
 const selected=useMemo(()=>select(data,f),[data,f]),strata=useMemo(()=>summarize(selected,f),[selected,f]);
 const total=stats(selected,f.basis),opts={group_scores:groupScores,group_conditions:groupConditions,per_page:perPage};
 const groups=useMemo(()=>galleryGroups(selected,f,opts),[selected,f,groupScores,groupConditions,perPage]);
 const reportPages=kind==='points'?selected.length:kind==='gallery'?groups.reduce((n,g)=>n+Math.ceil(g.points.length/perPage),0):1+strata.reduce((n,s)=>n+Math.ceil(s.conditions.length/5)+1,0);
 const conditionValues=[...new Set(select(data,{...DEFAULT_FILTERS,scope:filters.scope,substrates:filters.substrates}).map(condition))].sort(natural);
 const substrateValues=[...new Set(data.map(substrate))].sort(natural),batchValues=[...new Set(data.map(p=>p.project_id||'unknown'))].sort(natural);
 const fixedValues=[...new Set(data.map(p=>String(axis==='time'?p.power:p.time)))].sort(natural);
 const openDetail=(label,a)=>{setDetail({label,points:a});setDetailPage(0)};
 useEffect(()=>{try{const old=JSON.parse(localStorage.getItem('uvtape:researchReport')||'null');if(old?.id)setJob(old)}catch{}},[]);
 useEffect(()=>{
   if(!job?.id||['completed','failed','interrupted','expired'].includes(job.status))return;
   let cancelled=false,timer;
   const poll=async()=>{try{const r=await fetch(`${api}/api/research/reports/${job.id}`,{cache:'no-store',signal:AbortSignal.timeout(20000)});if(!r.ok){if(r.status===404||r.status===410){const next={...job,status:'expired',message:'보고서가 만료되었거나 서버가 재시작되었습니다. 다시 생성해 주세요.'};if(!cancelled){setJob(next);localStorage.setItem('uvtape:researchReport',JSON.stringify(next))}return}throw Error(`HTTP ${r.status}`)}const next=await r.json();if(!cancelled){setJob(next);localStorage.setItem('uvtape:researchReport',JSON.stringify(next));setError('');if(!['completed','failed','interrupted'].includes(next.status))timer=setTimeout(poll,3000)}}catch(e){if(!cancelled){setError('보고서 상태 연결을 재시도 중입니다. '+e.message);timer=setTimeout(poll,6000)}}};poll();return()=>{cancelled=true;clearTimeout(timer)};
 },[job?.id,job?.status,api]);
 useEffect(()=>{const onKey=e=>{if(e.key==='Escape'){if(evidence)setEvidence(null);else setDetail(null)}};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[evidence]);
 async function exportReport(format,overrideKind){setError('');setSubmitting(true);try{const payload={cohort:{...f,point_ids:selected.map(p=>p.id)},kind:overrideKind||kind,format,include_verification:includeVerification,per_page:perPage,group_scores:groupScores,group_conditions:groupConditions};if(payload.kind==='summary'){payload.cohort.results=null;payload.cohort.score_bands=null}const r=await fetch(`${api}/api/research/reports`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const j=await r.json();if(!r.ok)throw Error(typeof j.detail==='string'?j.detail:JSON.stringify(j.detail));setJob(j);localStorage.setItem('uvtape:researchReport',JSON.stringify(j))}catch(e){setError(e.message)}finally{setSubmitting(false)}}
 const downloadCSV=()=>{const a=document.createElement('a'),u=URL.createObjectURL(new Blob([csv(selected,f)],{type:'text/csv;charset=utf-8'}));a.href=u;a.download='EDS_selected_points.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
 const jobActive=job&&['preparing','queued','running'].includes(job.status);
 const basisText=f.basis==='final'?'사용자 검증 우선':'현재 C/O 규칙만';
 return <div className="content rs"><div className="intro"><div><span className="badge">{mode==='reports'?<FileText size={13}/>:<GitCompare size={13}/>} UV TAPE RESIDUE RESEARCH</span><h2>{titleOf(mode)}</h2><p>{mode==='reports'?'선택한 데이터와 근거 이미지를 같은 기준으로 출력합니다.':'플라즈마 조건, 웨이퍼 위치, 조건을 통합한 위치 경향을 비교합니다.'}</p></div><div className="rs-actions">{mode!=='reports'&&<button className="primary" onClick={()=>{patch({conditions:f.conditions,results:null,score_bands:null});go('Reports')}}><FileText size={14}/> 이 선택으로 보고서</button>}<button className="secondary" onClick={downloadCSV} disabled={!selected.length}><Download size={14}/> CSV</button></div></div>
 <div className="rs-position-key">{[[1,'Corner'],[4,'Edge'],[5,'Middle']].map(([w,label])=><span key={w}><i style={{background:POSITION_COLORS[w]}}/>W{w}<b>{label}</b></span>)}<small>각 위치 P1–P9 · W9는 기판별 Reference로 분리</small></div>
 <section className="panel rs-filters"><div className="rs-filter-grid"><label>데이터 범위<select value={filters.scope} onChange={e=>{patch({scope:e.target.value,conditions:null,wafers:null});setAxis('all')}}><option value="main">MAIN · W1 / W4 / W5</option><option value="reference">W9 · Reference</option><option value="other">기타 위치</option></select></label><label>기판<select value={filters.substrates?.[0]||'ALL'} onChange={e=>patch({substrates:e.target.value==='ALL'?null:[e.target.value]})}><option value="ALL">전체 · 기판별 별도 집계</option>{substrateValues.map(v=><option key={v}>{v}</option>)}</select></label><label>판정 기준<select value={filters.basis} onChange={e=>patch({basis:e.target.value})}><option value="final">사용자 검증 우선</option><option value="auto">현재 C/O 규칙만</option></select></label><label>검증 상태<select value={filters.review} onChange={e=>patch({review:e.target.value})}><option value="all">전체 Point</option><option value="verified">사용자 검증 완료</option><option value="unverified">미검증만</option></select></label><label>배치<select value={filters.batches?.[0]||'ALL'} onChange={e=>patch({batches:e.target.value==='ALL'?null:[e.target.value]})}><option value="ALL">전체 업로드 배치</option>{batchValues.map(v=>{const p=projectList.find(x=>x.id===v);return <option key={v} value={v}>{p?.created_at?`${p.created_at.slice(0,10)} · `:''}{p?.files?.[0]||v}</option>})}</select></label><label>웨이퍼 위치<select value={filters.wafers?.[0]||'ALL'} onChange={e=>patch({wafers:e.target.value==='ALL'?null:[Number(e.target.value)]})}><option value="ALL">범위 내 모든 위치</option>{(filters.scope==='main'?[1,4,5]:filters.scope==='reference'?[9]:[2,3,6,7,8]).map(w=><option key={w} value={w}>W{w} · {LOCATIONS[w]||'Other'}</option>)}</select></label></div>
 <div className="rs-selection-head"><b>플라즈마 조건</b><div><select aria-label="조건 비교 방식" value={axis} onChange={e=>{const v=e.target.value;setAxis(v);setFixed([...new Set(data.map(p=>String(v==='time'?p.power:p.time)))].sort(natural)[0]||'')}}><option value="all">전체 Power / Time</option><option value="time">Power 고정 · Time 비교</option><option value="power">Time 고정 · Power 비교</option></select>{axis!=='all'&&<select aria-label="고정 조건" value={fixed} onChange={e=>setFixed(e.target.value)}>{fixedValues.map(v=><option key={v}>{v}</option>)}</select>}<button className="secondary" onClick={()=>patch({conditions:null})}>전체</button><button className="secondary" onClick={()=>patch({conditions:[]})}>해제</button></div></div><PillSet values={conditionValues} value={filters.conditions} set={conditions=>patch({conditions})}/></section>
 <div className="rs-metrics"><Metric title="선택된 Point" value={total.n} note={`${strata.length} 기판 그룹 · ${new Set(selected.map(condition)).size} 조건`}/><Metric title="Residue" value={total.residue} note="C/O 기반 스크리닝 판정"/><Metric title="Ambiguous" value={total.ambiguous} note="불명확한 판정은 별도 유지"/><Metric title="검증 완료" value={`${total.verified} / ${total.n}`} note={basisText}/></div>
 {analysisActive&&<p className="rs-notice">분석이 진행 중입니다. 현재 불러온 데이터 기준이며 보고서 생성은 분석 작업이 끝난 뒤 실행됩니다.</p>}
 {!selected.length&&<section className="panel rs-empty"><GitCompare size={30}/><h3>선택 범위에 Point가 없습니다</h3><p>조건, 기판, 검증 상태 또는 출력 필터를 확인해 주세요.</p></section>}
 {mode!=='reports'&&selected.length>0&&<><div className="rs-tabs">{[['conditions','조건 비교'],['locations','위치별 조건'],['pooled','위치 통합'],['coverage','측정 현황']].map(([k,v])=><button key={k} aria-pressed={tab===k} className={tab===k?'selected':''} onClick={()=>setTab(k)}>{v}</button>)}</div>
 {strata.map(s=>{const base=s.conditions.find(c=>c.key===baseline)||s.conditions[0];return <section className="panel rs-stratum" key={s.substrate}><div className="rs-section-head"><div><label>{s.substrate} / {filters.scope.toUpperCase()}</label><h3>{tab==='conditions'?'플라즈마 조건 × Wafer 위치':tab==='locations'?'위치별 플라즈마 조건 경향':tab==='pooled'?'조건을 통합한 위치 비교':'P1–P9 측정 분포'}</h3><p>{tab==='pooled'?'관측 수에 따른 합산과 공통 조건의 동일 가중 평균을 구분합니다.':'Residue Point / 관측 Point · 미측정은 0%로 표시하지 않습니다.'}</p></div>{tab==='conditions'&&<label>기준 조건<select value={base.key} onChange={e=>setBaseline(e.target.value)}>{s.conditions.map(c=><option key={c.key}>{c.key}</option>)}</select></label>}</div><Legend/>
 {tab==='conditions'&&<div className="rs-scroll"><table className="rs-matrix"><thead><tr><th>Power / Time</th>{s.positions.map(p=><th key={p.wafer}>W{p.wafer} · {LOCATIONS[p.wafer]||'Other'}</th>)}<th>위치 간 차이</th></tr></thead><tbody>{s.conditions.map(c=><tr key={c.key}><th>{c.key}{c.key===base.key&&<em>기준</em>}<small>{c.batches} 배치 · {c.n} points</small></th>{c.cells.map(x=>{const b=base.cells.find(t=>t.wafer===x.wafer);return <td key={x.wafer}><button className={`rs-cell ${!x.n?'missing':''}`} disabled={!x.n} onClick={()=>openDetail(`${s.substrate} · ${c.key} · W${x.wafer}`,x.points)} style={x.n?{background:`rgba(193,91,100,${.02+(x.rate/100)*.14})`}:{}}><b>{pct(x.rate)}</b><span>{x.residue} / {x.n} points</span><Stack s={x}/><small>Non-residue {x.non} · 보류 {x.ambiguous}</small><small>검증 {x.verified}/{x.n}</small><em>{c.key===base.key?'기준':`Δ ${delta(x.n&&b?.n?x.rate-b.rate:null)}`}</em></button></td>})}<td className="rs-spread"><b>{c.spread==null?'—':`${fmt(c.spread)} pp`}</b><small>최대 − 최소</small></td></tr>)}</tbody></table></div>}
 {tab==='locations'&&<div className="rs-chart">{s.positions.map(pos=><div className="rs-chart-group" key={pos.wafer}><h4 style={{color:POSITION_COLORS[pos.wafer]}}>W{pos.wafer} · {LOCATIONS[pos.wafer]||'Other'}</h4><div className="rs-scale"><span/>{[0,25,50,75,100].map(n=><small key={n}>{n}%</small>)}</div>{s.conditions.map(c=>{const x=c.cells.find(x=>x.wafer===pos.wafer);return <RateBar key={c.key} label={c.key} value={x.rate} upper={x.upper} color={POSITION_COLORS[pos.wafer]} note={`${x.residue}/${x.n}`} onClick={x.n?()=>openDetail(`${c.key} · W${pos.wafer}`,x.points):null}/>})}</div>)}</div>}
 {tab==='pooled'&&<><div className="rs-pooled"><div><h4>전체 Point 합산</h4><p>선택된 모든 조건의 관측 수로 가중됩니다.</p>{s.positions.map(p=><RateBar key={p.wafer} label={`W${p.wafer} ${LOCATIONS[p.wafer]||'Other'}`} value={p.rate} upper={p.upper} color={POSITION_COLORS[p.wafer]} note={`${p.residue}/${p.n}`}/>)}</div><div><h4>공통 조건 균등 비교</h4><p>각 위치에 모두 존재하는 {s.common.length}개 조건을 같은 비중으로 계산합니다.</p>{s.positions.map(p=><RateBar key={p.wafer} label={`W${p.wafer} ${LOCATIONS[p.wafer]||'Other'}`} value={p.balanced} upper={p.balancedUpper} color={POSITION_COLORS[p.wafer]} note={`${p.common} conditions`}/>)}</div></div><div className="rs-footnote">공통 조건: {s.common.join(' · ')||'없음 — 위치별 측정 조건을 먼저 맞춰 주세요.'}<br/>균등 비교는 조건 구성 차이를 줄이는 기술통계입니다. 플라즈마 영향을 제거한 인과적 위치 효과를 뜻하지 않습니다.</div></>}
 {tab==='coverage'&&<div className="rs-scroll"><table className="rs-table"><thead><tr><th>Condition / batch</th><th>Wafer</th>{Array.from({length:9},(_,i)=><th key={i}>P{i+1}</th>)}</tr></thead><tbody>{s.conditions.flatMap(c=>[...new Set(c.points.map(p=>p.project_id||'unknown'))].sort(natural).flatMap(batch=>c.cells.map(cell=><tr key={`${c.key}-${batch}-${cell.wafer}`}><th>{c.key}<small>{batch.slice(0,12)}</small></th><th>W{cell.wafer}<small>{LOCATIONS[cell.wafer]||'Other'}</small></th>{Array.from({length:9},(_,i)=>{const a=cell.points.filter(p=>(p.project_id||'unknown')===batch&&Number(p.point)===i+1),cl=a.length===1?decision(a[0],f.basis):null;return <td key={i}><button disabled={!a.length} className={`rs-dot ${cl==='Residue'?'res':cl==='Non-residue'?'non':cl?'amb':''}`} onClick={()=>openDetail(`${c.key} W${cell.wafer} P${i+1}`,a)} title={a.length>1?`${a.length} records at same batch/W/P`:cl||'미측정'}>{a.length>1?`${a.length}건`:a.length?'●':'—'}</button></td>})}</tr>)))}</tbody></table></div>}
 <div className="rs-footnote">{tab==='coverage'?`관측된 배치 기준 P1–P9 고유 슬롯을 확인합니다. 같은 배치·W·P 중복 기록 ${s.conditions.reduce((n,c)=>n+c.duplicates,0)}건. 전체 배치 자체의 누락은 이 표만으로 확인할 수 없습니다.`:'비율의 분모에는 Ambiguous가 포함됩니다. 막대의 연한 부분은 Ambiguous를 모두 Residue로 가정했을 때까지이며, 신뢰구간이 아닙니다.'}</div></section>})}
 <details className="panel rs-method"><summary>판정 기준과 통계 해석 안내</summary><p>C ≥ 2.40×와 O ≥ 3.00× 기준을 적용하며 사용자 검증 판정을 우선합니다. 여기서 Residue는 UV tape 유래가 의심되는 스크리닝 분류이며, C/O 증가만으로 발생원을 확정하지 않습니다. Non-residue도 ‘모든 종류의 잔사가 없음’을 뜻하지 않습니다.</p><p>잔사 Point 비율은 면적률·입자 밀도·제거율·수율과 다릅니다. 동일 W/P 번호를 같은 물리 시료의 전후 측정으로 연결하지 않습니다. 점수 평균으로 최적 조건을 순위 매기지 않습니다.</p></details></>}
 {mode==='reports'&&<><section className="panel rs-report-options"><div className="rs-section-head"><div><label>01 / REPORT TYPE</label><h3>출력 구성</h3></div></div><div className="rs-report-kinds">{[['summary','조건·위치 요약','비교 표 + 위치 통합 결과'],['points','Point 상세','1 Point = 1장 · SEM / EDS / C / O'],['gallery','원본 SEM 모음','점수 구간별 원본 이미지 모아보기']].map(([k,t,d])=><button key={k} aria-pressed={kind===k} className={kind===k?'selected':''} onClick={()=>{setKind(k);setPreviewGroup(0)}}><b>{t}</b><span>{d}</span></button>)}</div>
 {kind!=='summary'&&<div className="rs-output-filters"><label>출력할 판정</label><PillSet values={CLASSES} value={filters.results} set={results=>patch({results})}/><label>점수 구간 · 판정과 독립적인 출력 필터</label><PillSet values={BANDS} value={filters.score_bands} set={score_bands=>patch({score_bands})} labeler={x=>BAND_LABELS[x]}/><small>70–&lt;80 / 80–&lt;90 / 90–100으로 경계를 구분합니다. Human 판정이 Residue여도 점수가 70 미만일 수 있습니다.</small></div>}
 <div className="rs-check-options">{kind==='points'&&<label><input type="checkbox" checked={includeVerification} onChange={e=>setIncludeVerification(e.target.checked)}/> 검증 정보와 저장된 수동 ROI 윤곽 포함</label>}{kind==='gallery'&&<><label>한 페이지 이미지 수 <select value={perPage} onChange={e=>setPerPage(Number(e.target.value))}>{[10,12,16,20].map(n=><option key={n} value={n}>{n}장</option>)}</select></label><label><input type="checkbox" checked={groupScores} onChange={e=>setGroupScores(e.target.checked)}/> 점수 구간마다 새 페이지</label><label><input type="checkbox" checked={groupConditions} onChange={e=>setGroupConditions(e.target.checked)}/> 플라즈마 조건마다 새 페이지</label></>}</div><div className="rs-footnote">{kind==='gallery'?'SEM 모음은 저장된 원본 SEM만 사용합니다. ROI·보정·크롭을 추가하지 않고 종횡비와 스케일바를 유지합니다. 이미지가 없으면 빈 자리와 누락 기록을 남깁니다.':kind==='points'?'원본 SEM, Full EDS, 원소 맵, C/O 맵을 한 장에 담습니다. Verification을 선택하면 최종 Human 판정·검증 시각·ROI 출처와 저장된 윤곽을 함께 표시합니다.':'요약 통계는 판정/점수 구간으로 제한하지 않고 선택한 조건·기판·검증 상태를 기준으로 계산합니다.'}</div></section>
 <section className="panel rs-export-panel"><div><label>02 / EXPORT SNAPSHOT</label><h3>{selected.length} Points · 예상 {selected.length?reportPages:0}장</h3><p>선택된 저장 데이터의 스냅샷으로 생성합니다. PPT/PDF + Point CSV + 필터·규칙·누락 목록을 ZIP으로 제공합니다.</p><small>대용량은 PPT/PDF 파일을 자동 분할합니다. 완료 파일은 서버 임시 보관으로 24시간 내 다운로드하세요.</small></div><div className="rs-actions"><button className="primary" disabled={!selected.length||submitting||jobActive} onClick={()=>exportReport('pptx')}><Download size={14}/> PPTX 생성</button><button className="secondary" disabled={!selected.length||submitting||jobActive} onClick={()=>exportReport('pdf')}><Download size={14}/> PDF 생성</button></div></section>
 {kind==='gallery'&&groups.length>0&&<section className="panel rs-preview"><div className="rs-section-head"><div><label>03 / PREVIEW</label><h3>원본 SEM 배치 미리보기</h3><p>첫 페이지 · 실제 출력은 조건/판정/점수 그룹별로 이어집니다.</p></div><select aria-label="미리보기 그룹" value={Math.min(previewGroup,groups.length-1)} onChange={e=>setPreviewGroup(Number(e.target.value))}>{groups.map((g,i)=><option key={JSON.stringify(g.key)} value={i}>{g.key.map(x=>BAND_LABELS[x]||x).join(' · ')} ({g.points.length})</option>)}</select></div><div className="rs-gallery-preview" style={{gridTemplateColumns:`repeat(${perPage===10||perPage===20?5:4},minmax(0,1fr))`}}>{groups[Math.min(previewGroup,groups.length-1)].points.slice(0,perPage).map(p=><div key={p.id}>{p.assets?.sem?<img loading="lazy" src={p.assets.sem.startsWith('http')?p.assets.sem:`${api}${p.assets.sem}`} alt={`Original SEM W${p.wafer} P${p.point}`} onError={e=>{e.currentTarget.style.display='none';e.currentTarget.nextElementSibling.hidden=false}}/>:null}<span hidden={!!p.assets?.sem}>SEM 이미지 없음</span><b>{p.power} · {p.time} · W{p.wafer} P{p.point}</b><small>{decision(p,f.basis)} · Score {fmt(p._score)}</small></div>)}</div></section>}
 </>}
 {error&&<div role="alert" className="rs-notice">{error}</div>}
 {job&&<section className="panel rs-job"><div><b>{job.status==='completed'?'보고서 생성 완료':job.status==='queued'?'보고서 대기 중':job.status==='running'?'보고서 생성 중':job.status}</b><p>{job.status==='completed'?'보고서와 선택 데이터가 준비되었습니다.':job.status==='queued'?'앞선 분석 또는 보고서 작업이 끝나면 시작합니다.':job.status==='running'?'선택한 Point와 이미지를 출력하고 있습니다.':job.message}</p><small>{job.n||0} Points · {job.pages||0} pages{job.parts?` · ${job.parts} files`:''}{job.missing_assets?` · 이미지 누락 ${job.missing_assets}건 (manifest 확인)`:''}</small></div>{jobActive&&<progress value={job.progress||0} max="100"/>}{job.status==='completed'&&<a className="primary" href={`${api}/api/research/reports/${job.id}/download`}>ZIP 다운로드</a>}{!jobActive&&<button className="secondary" onClick={()=>{setJob(null);localStorage.removeItem('uvtape:researchReport')}}>닫기</button>}</section>}
 {detail&&<div className="rs-overlay" onClick={()=>setDetail(null)}><section className="rs-detail" role="dialog" aria-label="측정 Point 상세" aria-modal="true" onClick={e=>e.stopPropagation()}><div className="rs-section-head"><div><h3>{detail.label}</h3><p>{detail.points.length} points</p></div><button className="secondary" aria-label="상세 닫기" onClick={()=>setDetail(null)}><X size={18}/></button></div><div className="rs-detail-list">{detail.points.slice(detailPage*24,(detailPage+1)*24).map(p=><button key={p.id} onClick={()=>setEvidence(p)}><div><b>W{p.wafer} P{p.point} · {decision(p,f.basis)}</b><small>{p._human?'검증 완료':'미검증'} · {substrate(p)} · ID {p.id}</small></div><span><Images size={15}/> 근거 이미지 <ChevronRight size={14}/></span></button>)}</div><div className="rs-detail-pages"><button className="secondary" disabled={!detailPage} onClick={()=>setDetailPage(x=>x-1)}>이전</button><span>{detailPage+1} / {Math.ceil(detail.points.length/24)}</span><button className="secondary" disabled={(detailPage+1)*24>=detail.points.length} onClick={()=>setDetailPage(x=>x+1)}>다음</button></div></section></div>}
 {evidence&&renderEvidence(evidence,()=>setEvidence(null))}
 </div>
}
