"use client";
import {useMemo,useState} from 'react';
import {Upload,GitCompare,FileText,ChevronRight,Search,Check,Activity,Database} from 'lucide-react';
const isVerified=p=>['Residue','Non-residue','Ambiguous'].includes(p.human_result);
const jobLabels={completed:'분석 완료',partial:'일부 저장 · 확인 필요',failed:'분석 실패',interrupted:'분석 중단',cancelled:'분석 취소',queued:'분석 대기',processing:'분석 진행 중'};
export default function WorkspaceDashboard({points,classify,go,onCondition,onPoint,dataState,jobs,openJob}){
 const [query,setQuery]=useState('');
 const groups=useMemo(()=>{const rows=new Map();for(const p of points){const condition=`${p.power||'—'} / ${p.time||'—'}`,substrate=p.substrate_type||p.features?.substrate_type||'미지정',key=`${condition}|${substrate}`;if(!rows.has(key))rows.set(key,{key,condition,substrate,points:[]});rows.get(key).points.push(p)}return [...rows.values()].sort((a,b)=>a.condition.localeCompare(b.condition,undefined,{numeric:true})||a.substrate.localeCompare(b.substrate))},[points]);
 const conditions=new Set(groups.map(g=>g.condition)).size,verified=points.filter(isVerified).length,ambiguous=points.filter(p=>classify(p)==='Ambiguous');
 const target=ambiguous.find(p=>!isVerified(p))||points.find(p=>!isVerified(p));
 const rows=groups.filter(g=>`${g.condition} ${g.substrate}`.toLowerCase().includes(query.toLowerCase())),unknown=dataState!=='ready'&&!points.length;
 const job=jobs?.[0];
 return <div className="content workspaceDashboard">
  <div className="intro"><div><div className="pageEyebrow">SEM / EDS WORKSPACE</div><h2>분석 현황</h2><p>저장된 측정 조건과 검증 진행 상황을 확인하세요.</p></div><button className="primary" onClick={()=>go('New Analysis')}><Upload size={16}/>새 분석</button></div>
  <div className="overviewMetrics">{[['저장된 Point',points.length,'전체 위치 · 누적 데이터'],['플라즈마 조건',conditions,'Power / Time 조합'],['검증 대기',points.length-verified,'사용자 판정 미완료'],['Ambiguous',ambiguous.length,'자동·검증 판정 중 보류']].map(([t,v,d])=><div className="metric" key={t}><small>{t}</small><b>{unknown?'—':v.toLocaleString()}</b><span>{unknown?'데이터 확인 필요':d}</span></div>)}</div>
  {job&&<button className="jobSummary" onClick={openJob}><Activity size={20}/><div><b>{jobLabels[job.status]||'최근 분석 상태'}</b><span>{job.files?.join(', ')||'최근 등록한 분석 작업'}</span></div><strong>{Math.round(job.progress||0)}%</strong><ChevronRight size={18}/></button>}
  {!!points.length&&<section className="reviewCallout"><div className="reviewCalloutIcon"><Check size={22}/></div><div><b>{target?'다음 Point를 검증하세요':'모든 Point의 사용자 판정이 저장되었습니다'}</b><p>{target?`${target.power} / ${target.time} · W${target.wafer} · P${target.point} — ${classify(target)==='Ambiguous'?'판정 보류 항목을 먼저 확인합니다.':'SEM과 C/O 근거를 확인하고 판정을 저장하세요.'}`:'조건·위치 비교에서 경향을 확인하고 보고서로 정리할 수 있습니다.'}</p></div><button className="secondary" onClick={()=>target?onPoint(target):go('Condition Compare')}>{target?'검증 이어가기':'비교 열기'}<ChevronRight size={16}/></button></section>}
  <section className="panel conditionInventory"><div className="inventoryHead"><div><h3>저장된 측정 조건</h3><p>기판별로 구분한 Point 수입니다. 조건을 선택하면 전체 측정 목록이 열립니다.</p></div><label className="search"><Search size={17}/><input aria-label="저장 조건 검색" value={query} onChange={e=>setQuery(e.target.value)} placeholder="조건 또는 기판 검색"/></label></div>
  {unknown?<div className="emptyPanel"><Database size={28}/><b>{dataState==='loading'?'저장 데이터를 확인하고 있습니다':'데이터 현황을 확인할 수 없습니다'}</b><small>{dataState==='loading'?'연결이 완료되면 측정 조건이 표시됩니다.':'상단의 다시 불러오기를 눌러 연결을 확인하세요.'}</small></div>:!points.length?<div className="emptyPanel"><Upload size={28}/><b>첫 분석을 시작하세요</b><small>EDS PDF와 측정 조건을 등록하면 이곳에 데이터가 누적됩니다.</small><button className="primary" onClick={()=>go('New Analysis')}>PDF 등록</button></div>:!rows.length?<div className="emptyPanel"><Search size={26}/><b>일치하는 조건이 없습니다</b><small>다른 조건이나 기판 이름으로 검색해 주세요.</small></div>:<div className="inventoryScroll"><table className="inventoryTable"><thead><tr><th>플라즈마 조건</th><th>기판</th><th>W1 <small>Corner</small></th><th>W4 <small>Edge</small></th><th>W5 <small>Middle</small></th><th>Reference / 기타</th><th>사용자 검증</th><th><span className="srOnly">상세 보기</span></th></tr></thead><tbody>{rows.map(g=>{const v=g.points.filter(isVerified).length;return <tr key={g.key}><th><button className="conditionLink" onClick={()=>onCondition(g.condition)}>{g.condition}<small>{g.points.length} Point</small></button></th><td><span className="substrateTag">{g.substrate}</span></td>{[1,4,5].map(w=><td key={w}>{g.points.filter(p=>Number(p.wafer)===w).length||'—'}</td>)}<td>{g.points.filter(p=>![1,4,5].includes(Number(p.wafer))).length||'—'}</td><td><div className="inventoryVerification"><span>{v} / {g.points.length}</span><div><i style={{width:`${100*v/g.points.length}%`}}/></div></div></td><td><button className="iconBtn" aria-label={`${g.condition} ${g.substrate} 상세 보기`} onClick={()=>onCondition(g.condition)}><ChevronRight size={17}/></button></td></tr>})}</tbody></table></div>}
  <div className="inventoryFooter"><span>MAIN · W1 Corner / W4 Edge / W5 Middle</span><span>배치별 P1–P9 충족 여부는 조건·위치 비교의 측정 현황에서 확인</span></div></section>
  <div className="workspaceShortcuts">{[[GitCompare,'조건·위치 비교','플라즈마 조건과 위치에 따른 판정 경향','Condition Compare'],[FileText,'보고서 출력','Point 상세 또는 원본 SEM을 PPTX / PDF로','Reports']].map(([Icon,title,desc,page])=><button key={page} onClick={()=>go(page)}><Icon size={22}/><div><b>{title}</b><span>{desc}</span></div><ChevronRight size={18}/></button>)}</div>
 </div>
}
