import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import {DEFAULT_FILTERS,select,summarize,band,galleryGroups} from '../app/researchModel.mjs';
const src=fs.readFileSync(new URL('../app/AppClient.js',import.meta.url),'utf8');const ctx={};vm.createContext(ctx);
for(const name of ['finiteNumber','elementRatioDisplayScore','coRatioDisplayScore','coRatioRuleResult','hasHumanROI','normalizeResultLabel','currentRatios','autoPointClass','pointClass','displayScore']){const start=src.indexOf('function '+name+'('),end=src.indexOf('\nfunction ',start+1);vm.runInContext(src.slice(start,end),ctx)}
const p=(id,w,cond,result,score=75)=>({id,project_id:'b1',power:cond,time:'30s',wafer:w,point:1,substrate_type:'SiCN',_final:result,_auto:result,_human:false,_score:score});
test('missing ratios do not become zero and erase stored labels',()=>{assert.equal(ctx.coRatioRuleResult(null,null),null);assert.equal(ctx.coRatioDisplayScore(null,null),null);assert.equal(ctx.pointClass({features:{result:'Residue'}}),'Residue');assert.equal(ctx.displayScore({features:{}}),null)});
test('current rule and Human override stay consistent',()=>{const a={features:{c_roi_global_ratio:2.4,o_roi_global_ratio:3}};assert.equal(ctx.pointClass(a),'Residue');assert.equal(ctx.displayScore(a),70);assert.equal(ctx.pointClass({...a,human_result:'Non-residue'}),'Non-residue')});
test('score bins are disjoint and include 100',()=>{assert.deepEqual([59.9,60,69.9,70,79.9,80,89.9,90,100,null].map(x=>band({_score:x})),['0-60','60-70','60-70','70-80','70-80','80-90','80-90','90-100','90-100','missing'])});
test('selection excludes W9 and deduplicates ID',()=>{const a=p('a',1,'150W','Residue'),b=p('b',9,'150W','Residue');assert.equal(select([a,a,b],DEFAULT_FILTERS).length,1);assert.equal(select([a],{...DEFAULT_FILTERS,conditions:[]}).length,0)});
test('equal-condition location comparison uses only common conditions',()=>{const a=[p('1',1,'150W','Residue'),p('2',4,'150W','Non-residue'),p('3',5,'150W','Ambiguous'),p('4',1,'350W','Non-residue')];const s=summarize(a,DEFAULT_FILTERS)[0];assert.deepEqual(s.common,['150W / 30s']);assert.equal(s.positions[0].rate,50);assert.equal(s.positions[0].balanced,100);assert.equal(s.conditions[1].spread,null)});
test('gallery separates decision classes and score bins',()=>{const a=[p('a',1,'150W','Residue',75),p('b',1,'150W','Non-residue',75),p('c',1,'150W','Residue',85)];assert.equal(galleryGroups(a,DEFAULT_FILTERS,{group_conditions:false,group_scores:true}).length,3)});
